### ISSUE TITLE
Bot fails to Update

### ISSUE THREAD

**Issue by HariSK20** [AJAYK-01/KTU-Notifier#13]
**Describe the bug**
While trying to run the bot, the scrapper function returns an empty list and fails to send notifications. 
While trying to run scrape() function in scrapper.py, It returns the following error: 
```list index out of range```

**To Reproduce**
1. Run the function scrape() from scrapper.py

**Expected behavior**
scrapper.py returns non-empty array of announcements

**Screenshots**
![image](https://user-images.githubusercontent.com/56635847/135714430-3f4936e9-2473-44e7-b747-b811d6f12f6b.png)

**Additional context**
Error is supposedly produced while trying to parse an announcement which is in a different format as shown below
![image](https://user-images.githubusercontent.com/56635847/135718832-eb617afc-a08e-4383-8a4e-1f9d8ffd56b6.png)

**Comment by HariSK20** [comment]
I may have a solution and I would like to work on it

**Comment by AJAYK-01** [comment]
> **Describe the bug** While trying to run the bot, the scrapper function returns an empty list and fails to send notifications. While trying to run scrape() function in scrapper.py, It returns the following error: `list index out of range`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Run the function scrape() from scrapper.py
> 
> **Expected behavior** scrapper.py returns non-empty array of announcements
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/56635847/135714430-3f4936e9-2473-44e7-b747-b811d6f12f6b.png)
> 
> **Additional context** Error is supposedly produced while trying to parse an announcement which is in a different format as shown below ![image](https://user-images.githubusercontent.com/56635847/135718832-eb617afc-a08e-4383-8a4e-1f9d8ffd56b6.png)

Yea the bot is currently offline due to scraping bugs and I haven't got time to lookup on the issue yet.

Thank you for pointing out the issue!!

**Comment by AJAYK-01** [comment]
> I may have a solution and I would like to work on it

Sure!
