### ISSUE TITLE
Python Version Support

### ISSUE THREAD

**Issue by RamesanPP** [AJAYK-01/KTU-Notifier#17]
The packages in `requirements.py` are mostly deprecated and not available in latest python versions.
The packages for numpy1.19.1 and tensorflow2.0.0  needs Python Version 3.7 or lower
Yet the package `pycrypto` is deprecated and unsupported in python versions 3.3 and above
Therefore, package ***pycrypto*** must be changed to ***pycryptodome***.
(Use ***pycryptodome*** instead! It is a project still maintained (june 2017) and includes the functions of pycrypto for python 3.xx (It worked for me on python 3.7) Refer this link for more details : https://www.pycryptodome.org/en/latest/index.html )

Or else please specify the exact version number on which the project is built/currently is working.

**Comment by AJAYK-01** [comment]
tensorflow 2.0 is too huge for the free tier of heroku, hence sticking on to the lower version here

**Comment by AJAYK-01** [comment]
The current requirements seem to satisfy the deployment on heroku with runtime of Python 3.6.9. 
I don't understand what is the issue you are facing, could you elaborate your setup?
